In [ ]:
import numpy as np
np.arange(0,20,2)

In [ ]:
np.zeros((3,6))

In [ ]:
np.ones((4,6))

In [ ]:
np.random.randint(1,100,(6,6))

In [ ]:
import numpy as np
np.random.randint(0,100,10)

In [59]:
np.random.seed(1)
np.random.randint(0,100,10)

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1])

In [8]:
import numpy as np
np.random.seed(1)
np.random.randint(0,100,10)

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1])

In [9]:
np.random.seed(1)
myArray=np.random.randint(0,100,32)
print('this is my randon ones time array=========',myArray)
print('this is the maximum numner form my array==',myArray.max())
print('this is the minimum number from array=====',myArray.min())
print('this is the mean value of my array========',myArray.mean())
print('index  value of maximum numberin arary====',myArray.argmax())
print('index  value of manimum numberin arary====',myArray.argmin())
print('add the array in matrix form like ========',myArray.reshape(4,8))

this is my randon ones time array========= [37 12 72  9 75  5 79 64 16  1 76 71  6 25 50 20 18 84 11 28 29 14 50 68
 87 87 94 96 86 13  9  7]
this is the maximum numner form my array== 96
this is the minimum number from array===== 1
this is the mean value of my array======== 43.71875
index  value of maximum numberin arary==== 27
index  value of manimum numberin arary==== 9
add the array in matrix form like ======== [[37 12 72  9 75  5 79 64]
 [16  1 76 71  6 25 50 20]
 [18 84 11 28 29 14 50 68]
 [87 87 94 96 86 13  9  7]]


In [10]:
np.random.seed() # if we didnt menton any number as seed parameter our values will change continuesly it will not take once tiem random number
np.random.randint(0,100,100).reshape(10,10)

array([[37, 98, 64, 86, 64, 12, 41, 92, 99, 55],
       [29,  2, 67, 31, 89,  7, 39, 25, 87,  6],
       [31, 69, 43, 37, 92, 24, 67, 96, 49, 50],
       [68, 88, 92, 52,  8, 36, 97,  6, 97, 39],
       [69, 22, 36, 72, 18, 48, 25, 66, 33, 98],
       [ 4, 41, 29, 46, 24, 54, 58, 13, 49, 54],
       [67, 75, 41, 92, 95, 41,  0, 48, 10, 71],
       [53, 85, 72,  9, 35, 73, 20, 97,  1, 35],
       [78, 52, 76, 91, 10, 22, 75, 70, 64, 34],
       [30, 23, 57, 30, 28,  8, 77, 93, 21, 97]])

In [11]:
matrix =np.random.randint(0,100,100).reshape(10,10)
matrix

array([[82, 69, 80, 68, 39,  6, 78, 64, 96, 93],
       [80, 27, 81, 84, 79, 92, 31, 87,  9, 86],
       [75, 71, 15, 59, 99, 62, 81, 40, 10, 52],
       [53, 31,  7, 51, 72, 57, 94, 24, 37,  0],
       [35, 33, 80, 72, 77, 60,  8, 69, 39, 21],
       [77, 50, 95, 38, 93, 82, 70, 43, 68, 89],
       [53,  4, 86,  3, 58, 47, 79,  1, 41, 76],
       [34, 53, 57, 66, 70, 94, 26, 90, 66, 54],
       [63, 27, 16, 69, 19, 60, 82, 97, 40,  2],
       [20, 64, 65, 48, 36, 19, 39, 53, 57, 47]])

In [22]:
print(matrix[5,4])
print(matrix[3,7])

print(matrix[8,6])
print(matrix[:,0])#it will take 0 th  position coloumn.
print(matrix[:,3])#it will take 3 rd position coiulmn.
print(matrix[0,:])# it will take 0 th positon row.
print(matrix[7,:])# it will take 7th postion row.
print(matrix[0:3,0:5])# it will print the matrix row 3 and col 5

93
24
82
[82 80 75 53 35 77 53 34 63 20]
[68 84 59 51 72 38  3 66 69 48]
[82 69 80 68 39  6 78 64 96 93]
[34 53 57 66 70 94 26 90 66 54]
[[82 69 80 68 39]
 [80 27 81 84 79]
 [75 71 15 59 99]]
